server:
  port: 8072
spring:
  application:
    name: xxl-job-executor
xxl:
  job:
    accessToken: 6KWUjrRMNkq34Uxx
    admin:
      addresses: http://106.91.199.94:8071/xxl-job-admin
    executor:
      port: 9999
      appname: xxl-job-executor
      logpath: /xxl-job-logs
      logretentiondays: 30