server:
  port: 8082
spring:
  application:
    name: hom-service-b
  cloud:
    nacos:
      server-addr: 127.0.0.1:8000
      username: client
      password: h363WSxGId3x8QKBrAq9J1cKx5x9QpUq
      discovery:
        group: HOM_DEV_GROUP
        namespace: 12e6ef0b-3ab9-449c-8331-5c7cfcf5b9f7